-- ShedOS Hyprland autostart applications. hl.exec_cmd spawns async.

hl.on("hyprland.start", function()
    -- uwsm finalize signals compositor readiness for the Type=notify
    -- wayland-session unit; without it, greetd login loops.
    hl.exec_cmd("uwsm finalize")

    -- Apply GTK/icon/cursor theme via gsettings so apps that query
    -- org.gnome.desktop.interface (nautilus, GNOME Calendar, etc.) also
    -- pick up the active theme. The script is regenerated by `shedman
    -- theme apply` from /etc/shedos/system.toml [theme].
    hl.exec_cmd("bash /etc/shedos/themes/current/gsettings.sh")

    -- elephant feeds walker; required before any walker --provider
    -- call. Both run as long-lived daemons so Super+D / Super+C are
    -- instant (dbus toggles into the warm walker service).
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("/usr/lib/shedos/hyprland-position-fixer")
    hl.exec_cmd("jetbrains-toolbox --minimize")
    hl.exec_cmd("/usr/bin/shedos-user-session")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-- Long-running daemons (waybar, mako, hypridle, awww-daemon) are
-- systemd user units with Restart=on-failure, so they survive
-- individual crashes and respawn after a Hyprland restart. See:
--   /usr/lib/systemd/user/{waybar,mako,hypridle}.service  (upstream)
--   /usr/lib/systemd/user/shedos-wallpaper.service         (ShedOS)
